/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.AdvancedTasks.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AdvTaskMapping service. Represents a row in the &quot;AdvancedTasks_AdvTaskMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.AdvancedTasks.model.impl.AdvTaskMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.AdvancedTasks.model.impl.AdvTaskMappingImpl}.
 * </p>
 *
 * @author David Proba
 * @see AdvTaskMapping
 * @see com.liferay.AdvancedTasks.model.impl.AdvTaskMappingImpl
 * @see com.liferay.AdvancedTasks.model.impl.AdvTaskMappingModelImpl
 * @generated
 */
public interface AdvTaskMappingModel extends BaseModel<AdvTaskMapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a adv task mapping model instance should use the {@link AdvTaskMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this adv task mapping.
	 *
	 * @return the primary key of this adv task mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv task mapping.
	 *
	 * @param primaryKey the primary key of this adv task mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the at m ID of this adv task mapping.
	 *
	 * @return the at m ID of this adv task mapping
	 */
	public long getAtMId();

	/**
	 * Sets the at m ID of this adv task mapping.
	 *
	 * @param atMId the at m ID of this adv task mapping
	 */
	public void setAtMId(long atMId);

	/**
	 * Returns the at m task ID of this adv task mapping.
	 *
	 * @return the at m task ID of this adv task mapping
	 */
	public long getAtMTaskId();

	/**
	 * Sets the at m task ID of this adv task mapping.
	 *
	 * @param atMTaskId the at m task ID of this adv task mapping
	 */
	public void setAtMTaskId(long atMTaskId);

	/**
	 * Returns the at m dependent from ID of this adv task mapping.
	 *
	 * @return the at m dependent from ID of this adv task mapping
	 */
	public long getAtMDependentFromId();

	/**
	 * Sets the at m dependent from ID of this adv task mapping.
	 *
	 * @param atMDependentFromId the at m dependent from ID of this adv task mapping
	 */
	public void setAtMDependentFromId(long atMDependentFromId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AdvTaskMapping advTaskMapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AdvTaskMapping> toCacheModel();

	@Override
	public AdvTaskMapping toEscapedModel();

	@Override
	public AdvTaskMapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}