/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.ldx6demo.teamsitewall.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Wallpost service. Represents a row in the &quot;LDXTeamSiteWall_Wallpost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.ldx6demo.teamsitewall.model.impl.WallpostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.ldx6demo.teamsitewall.model.impl.WallpostImpl}.
 * </p>
 *
 * @author David Proba
 * @see Wallpost
 * @see com.liferay.ldx6demo.teamsitewall.model.impl.WallpostImpl
 * @see com.liferay.ldx6demo.teamsitewall.model.impl.WallpostModelImpl
 * @generated
 */
public interface WallpostModel extends BaseModel<Wallpost>, StagedGroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wallpost model instance should use the {@link Wallpost} interface instead.
	 */

	/**
	 * Returns the primary key of this wallpost.
	 *
	 * @return the primary key of this wallpost
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wallpost.
	 *
	 * @param primaryKey the primary key of this wallpost
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this wallpost.
	 *
	 * @return the uuid of this wallpost
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this wallpost.
	 *
	 * @param uuid the uuid of this wallpost
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the wallpost ID of this wallpost.
	 *
	 * @return the wallpost ID of this wallpost
	 */
	public long getWallpostId();

	/**
	 * Sets the wallpost ID of this wallpost.
	 *
	 * @param wallpostId the wallpost ID of this wallpost
	 */
	public void setWallpostId(long wallpostId);

	/**
	 * Returns the company ID of this wallpost.
	 *
	 * @return the company ID of this wallpost
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wallpost.
	 *
	 * @param companyId the company ID of this wallpost
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this wallpost.
	 *
	 * @return the group ID of this wallpost
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this wallpost.
	 *
	 * @param groupId the group ID of this wallpost
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this wallpost.
	 *
	 * @return the user ID of this wallpost
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this wallpost.
	 *
	 * @param userId the user ID of this wallpost
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wallpost.
	 *
	 * @return the user uuid of this wallpost
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this wallpost.
	 *
	 * @param userUuid the user uuid of this wallpost
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the post message of this wallpost.
	 *
	 * @return the post message of this wallpost
	 */
	@AutoEscape
	public String getPostMessage();

	/**
	 * Sets the post message of this wallpost.
	 *
	 * @param postMessage the post message of this wallpost
	 */
	public void setPostMessage(String postMessage);

	/**
	 * Returns the status of this wallpost.
	 *
	 * @return the status of this wallpost
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this wallpost.
	 *
	 * @param status the status of this wallpost
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this wallpost.
	 *
	 * @return the status by user ID of this wallpost
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this wallpost.
	 *
	 * @param statusByUserId the status by user ID of this wallpost
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this wallpost.
	 *
	 * @return the status by user uuid of this wallpost
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this wallpost.
	 *
	 * @param statusByUserUuid the status by user uuid of this wallpost
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this wallpost.
	 *
	 * @return the status by user name of this wallpost
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this wallpost.
	 *
	 * @param statusByUserName the status by user name of this wallpost
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this wallpost.
	 *
	 * @return the status date of this wallpost
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this wallpost.
	 *
	 * @param statusDate the status date of this wallpost
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the create date of this wallpost.
	 *
	 * @return the create date of this wallpost
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this wallpost.
	 *
	 * @param createDate the create date of this wallpost
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wallpost.
	 *
	 * @return the modified date of this wallpost
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wallpost.
	 *
	 * @param modifiedDate the modified date of this wallpost
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user name of this wallpost.
	 *
	 * @return the user name of this wallpost
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this wallpost.
	 *
	 * @param userName the user name of this wallpost
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this wallpost is approved.
	 *
	 * @return <code>true</code> if this wallpost is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this wallpost is denied.
	 *
	 * @return <code>true</code> if this wallpost is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this wallpost is a draft.
	 *
	 * @return <code>true</code> if this wallpost is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this wallpost is expired.
	 *
	 * @return <code>true</code> if this wallpost is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this wallpost is inactive.
	 *
	 * @return <code>true</code> if this wallpost is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this wallpost is incomplete.
	 *
	 * @return <code>true</code> if this wallpost is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this wallpost is pending.
	 *
	 * @return <code>true</code> if this wallpost is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this wallpost is scheduled.
	 *
	 * @return <code>true</code> if this wallpost is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.ldx6demo.teamsitewall.model.Wallpost wallpost);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.ldx6demo.teamsitewall.model.Wallpost> toCacheModel();

	@Override
	public com.liferay.ldx6demo.teamsitewall.model.Wallpost toEscapedModel();

	@Override
	public com.liferay.ldx6demo.teamsitewall.model.Wallpost toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}