/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BeaconDDL service. Represents a row in the &quot;BeaconDDL_BeaconDDL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.BeaconDDLModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.BeaconDDLImpl}.
 * </p>
 *
 * @author David Proba
 * @see BeaconDDL
 * @see com.liferay.sample.model.impl.BeaconDDLImpl
 * @see com.liferay.sample.model.impl.BeaconDDLModelImpl
 * @generated
 */
public interface BeaconDDLModel extends BaseModel<BeaconDDL> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a beacon d d l model instance should use the {@link BeaconDDL} interface instead.
	 */

	/**
	 * Returns the primary key of this beacon d d l.
	 *
	 * @return the primary key of this beacon d d l
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this beacon d d l.
	 *
	 * @param primaryKey the primary key of this beacon d d l
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this beacon d d l.
	 *
	 * @return the uuid of this beacon d d l
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this beacon d d l.
	 *
	 * @param uuid the uuid of this beacon d d l
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this beacon d d l.
	 *
	 * @return the ID of this beacon d d l
	 */
	public long getId();

	/**
	 * Sets the ID of this beacon d d l.
	 *
	 * @param Id the ID of this beacon d d l
	 */
	public void setId(long Id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.BeaconDDL beaconDDL);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.BeaconDDL> toCacheModel();

	@Override
	public com.liferay.sample.model.BeaconDDL toEscapedModel();

	@Override
	public com.liferay.sample.model.BeaconDDL toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}